FROM node:22-alpine

WORKDIR /app

# Копируем package.json и устанавливаем зависимости
COPY package*.json ./
RUN npm ci

# Копируем исходный код
COPY . .

# Устанавливаем переменные окружения
ENV NODE_ENV=development

EXPOSE 3000

CMD ["npm", "run", "dev"] 